dist: xenial
sudo: required

language: cpp

addons:
  artifacts: true

branches:
  only:
    - master
    - master_nc

cache:
    directories:
      - $HOME/.cache
 
env:
    global:
      # Environment variables for packaging
      - PRODUCT=flameshot
      #TODO: we should take version from the last tag in git history + build number
      - VERSION=0.7.12
      - RELEASE=1
      - ARCH=x86_64
      # Dockerfile from https://github.com/flameshotapp/flameshot-docker-images
      - DOCKER_REPO=vitzy/flameshot
      # Option: wetransfer.com, file.io, 0x0.st, transfer.sh
      - UPLOAD_SERVICE=wetransfer.com

# The actual list of distribution is available on
# https://hub.docker.com/r/vitzy/flameshot/tags/
matrix:
    include:
        - os: linux
          # 1 - Fedora 31
          env: OS=fedora DIST=31 EXTEN=rpm
          services: docker
        - os: linux
          # 2 - Fedora 32
          env: OS=fedora DIST=32 EXTEN=rpm
          services: docker
        - os: linux
          # 3 - Ubuntu 16.04 LTS
          env: OS=ubuntu DIST=xenial EXTEN=deb
          services: docker
        - os: linux
          # 4 - Ubuntu 18.04 LTS
          env: OS=ubuntu DIST=bionic EXTEN=deb
          services: docker
        - os: linux
          # 5 - Ubuntu 20.04 LTS
          env: OS=ubuntu DIST=focal EXTEN=deb
          services: docker
        - os: linux
          # 6 - Debian stretch
          env: OS=debian DIST=stretch EXTEN=deb
          services: docker
        - os: linux
          # 7 - Debian 9 (stretch)
          env: OS=debian DIST=stretch EXTEN=deb
          services: docker
        - os: linux
          # 8 - Debian 10 (buster)
          env: OS=debian DIST=buster EXTEN=deb
          services: docker
        - os: linux
          # 8
          # No docker environment, just for CI build & test
          # ubuntu xenial;  default Qt version is 5.6.1
          env: OS=ubuntu DIST=xenial EXTEN=other
#       - os: osx
#         # 9 - MacOS
#         compiler: clang
#         osx_image: xcode9.2

before_install:
  - export ROOT_PATH="$(pwd)"
  - chmod +x .travis/*.sh
  - chmod +x .travis/services/*.sh
  - if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then source .travis/linux_before_install.sh; fi

install:
  - if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then source .travis/linux_install.sh; fi

script:
# - git submodule update --init --recursive
# - git describe --long
  - if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then source .travis/linux_script.sh; fi
# - if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then source .travis/osx_script.sh; fi

#after_success:
#  - if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then source .travis/linux_after_success.sh; fi
#  - echo "Download URL is ${TEMP_DOWNLOAD_URL} "

# deploy:
#    # Deploy packages to Github Release
#    provider: releases
#    api_key: "GITHUB ENCYPTED OAUTH TOKEN"
#    file_glob: true
#    file: dist/*.{deb,rpm,AppImage,dmg}
#    skip_cleanup: true
#    on:
#      tags: true
#      branch: master
